## Numpy array and basics

In [1]:
import numpy as np

Creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


List vs Numpy array

In [4]:
py_list = [1, 2, 3]
print("Python list multiplication", py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication
print("Python array multiplication", np_array * 2)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.array(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time:  0.04829239845275879

 Numpy operation time:  0.0010027885437011719


Creating array from scratch

In [10]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("ones array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.19913116 0.13325728 0.45872062]
 [0.50593746 0.26592895 0.41312958]]
sequence array: 
 [0 2 4 6 8]


## Vector, Matric and Tensor

In [13]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Data Type ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Data Type  int64


### Array Reshaping

In [25]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\nReshaped array ", reshaped)

flattened = reshaped.flatten()
print("\nFattened array ", flattened)

raveled = reshaped.ravel()
print("\n revaled array ", raveled) # ravel returns instead of copy

# Transpose
transpose = reshaped.T
print("\n Transposed array\n", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Fattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 revaled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
