# Numpy Array Operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [6]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


### Sorting

In [10]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [11]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


Filter with mask

In [12]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [15]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [17]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### array compatibility

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) # vstack adds new row
print("Original\n", original)
print("\nWith new row\n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col)) # hstack adds new col
print("\nWith new col\n", with_new_col)

Original
 [[1 2]
 [3 4]]

With new row
 [[1 2]
 [3 4]
 [5 6]]

With new col
 [[1 2 7]
 [3 4 8]]


In [28]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion ", deleted) # deleted array is returned

Array after deletion  [1 2 4 5]
